### ISSUE TITLE
Patches are not downloaded properly

### ISSUE THREAD

**Issue by tanahy** [leycec/fsnrnue#3] opened 2020-04-18 21:48 UTC
First of all, thanks for making this possible, I already played the game but I wanted to test this version in case I could help with debugging.

I followed the instructions stated in the README for linux using the one clicker installer. Everything when just totally fine but all the patch files that were downloaded weighted between 0B and 3KiB. 

The issue is easily solved by downloading the patches from the google drive links in the Beast's Liar forum as stated in the instructions. However, I feel like this is not the intended behaviour and I should report it in case something weird is going on, as it happened with all the patches (I installed them all except the OP one).

**Comment by leycec** [comment] 2020-04-29 05:11
**Yup.** Thanks for publicly noting this, @tanah. Your dedication to the crème-de-la-crème of the visual novel world is commendable.

It's suspiciously concerning that the Ultimate Edition installer failed to properly fetch *any* patches for you. That's Critical Badness™ right there. In my case, the installer behaved less bad but still bad. Thus, the [FAQ entry that you astutely noted](https://github.com/leycec/fsnrnue#how-to-resolve-script-exception-raised-errors-at-startup). Specifically, the installer:

* Behaved as expected the first time I ran it (i.e., it properly fetched all patches).
* Behaved erratically the second time I ran it (i.e., it properly fetched only about ¾ of the patches, with the remainder exactly 0-byte).

誰も知らない! (*"Nobody knows why!"*) Something weird is *definitely* going on – but I'm unsure whether we can minimize that weirdness from our end. A Lutris script can only do so much and that's usually much less than anyone would like. My grim suspicion is that either:

* **[option 1]** The installer is calling some low-level (C|C++|C#) networking primitive that is currently poorly emulated under WINE and/or Mono.
* **[option 2]** The online service hosting these patches (*whatever that may be – I'm afraid I haven't delved into the source for the installer yet*) is fundamentally unreliable.

Option 1 seems likelier. In any case, a working alternative to both options would be for:

1. **Someone who is not me to upload these patches to a more reliable service than GoogleDrive.** [For reasons](https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive),<sup>*blame google*</sup> GoogleDrive links are *not* usable from automated scripts. The patches are too large to reasonably host at this repository. Moreover, attempting to do so given the content of several of the patches (*ahem H ahem*) would be a fantastic way to get this repository flagged and flogged by Microsoft. Let's please avoid that BAD END.
1. Refactor our Lutris installer to:
   1. **Automatically fetch *all* of these patches from that reliable service.** Yes, this is silly. The Ultimate Installer already fetches *all* of these patches and I don't recall there being any way to automatically disable that behaviour at the command-line. <sup>*...or is there?*</sup>
   1. **Automatically overwrite *all* of the patches fetched and installed by the Ultimate Installer with the patches fetched by our Lutris script.** Yes, it would be cleverer to attempt to detect for faulty patches with arcane and curmudgeonly Bash commands (e.g., [some variant on](https://superuser.com/questions/204564/how-can-i-find-files-that-are-bigger-smaller-than-x-bytes) `find . -type f -size -4096c`), but that would then require writing a full-blown Bash script that would then need to somehow conditionally invoke `curl` or `wget` on as as-needed basis, and I'm unsure that Lutris even allows that sort of dangerous shenanigans. For security, it probably shouldn't. In short, ain't nobody got that kinda time or sanity. <sup>*...or do they? I don't, but maybe you or someone else does! Please write me this script, somebody.*</sup>

This is starting to look ugly and risky and I'm all out of bubblegum. Rather than actually doing anything, let's leave this issue open and see if anyone has any brighter ideas than my shameless rambling above.

**Comment by leycec** [comment] 2020-04-29 05:19
**Ahah!** @gourrykun [helpfully identified the culprit](https://github.com/leycec/fsnrnue/issues/2#issuecomment-620439559) at #1:

> Currently this step often fails due to disk quota exceeded.

Welp. It was Option 2 after all. `</sigh>`

On the bright side, this isn't our fault. On the dark side, the Ultimate Installer team at [Beast's Lair](https://forums.nrvnqsr.com) now desperately needs to upload their patchset to a more reliable host. For reasons stated above, that can't be GitHub and shouldn't be GoogleDrive. If anyone who is not me would like to open up a discussion with our [Beast's Lair sempais](https://forums.nrvnqsr.com) about this, that would be just great.

Until then, our hands are gently tied by Ilya.

**Comment by leycec** [comment] 2020-09-12 03:29
[Status update on repository inactivity with apologies](https://github.com/leycec/fsnrnue/issues/2#issuecomment-691380481). `</sigh>`

**Comment by wachiragetkul** [comment] 2020-12-31 07:30
> First of all, thanks for making this possible, I already played the game but I wanted to test this version in case I could help with debugging.
> 
> I followed the instructions stated in the README for linux using the one clicker installer. Everything when just totally fine but all the patch files that were downloaded weighted between 0B and 3KiB.
> 
> The issue is easily solved by downloading the patches from the google drive links in the Beast's Liar forum as stated in the instructions. However, I feel like this is not the intended behaviour and I should report it in case something weird is going on, as it happened with all the patches (I installed them all except the OP one).

**Comment by kaasknak** [comment] 2021-07-19 16:06
I am also running into the problem of patches not being downloaded and manual patches being unavailable due to google drive saying too many people downloaded it already. I am however not sure if that is the only issue since I am also using ubuntu 20.04 and as you mentioned here https://github.com/leycec/fsnrnue/issues/14#issuecomment-879578177 there could be a problem with that as well.

Would this be fixable or would it be best to hope for version 1.0 finally hitting?
I even considered installing windows in a virtualbox (shudders). Would this be a better option?

**Comment by leycec** [comment] 2021-07-20 04:16
> ...and manual patches being unavailable due to google drive saying too many people downloaded it already.

**Yikes.** I've long suspected this was infrequently happening. It's mildly depressing to learn this is now frequently happening and may even be the "new normal."

> I am however not sure if that is the only issue...

Fortunately, that's the only outstanding issue I know of. Every other issue usually reduces to: "Your Vulkan, DXVK, and/or D3D9 drivers are broken. Please fix them."

So, you can at least be consoled (in the oppressive darkness of yet another filthy hot midsummer's evening with a busted air conditioner, a tap that only runs lukewarm, and five dogs that drape themselves across your prone body as you fitfully fail to sleep) that what you're seeing is almost certainly failing patches. :sob: 

That's it. Admittedly, not even being able to download patches is a bit of a hard blocker.

> Would this be a better option?

The best option would be for you to graciously do everyone in the Linux *Fate/stay night* community a heroic and painfully self-sacrificial favour. I wouldn't normally beg, I swear! But...

You seem like you're desperately keen. I can hardly blame you. *Fate/stay night* is one of the better and crazier things I've ever read – and I actually read books. Like, voluntarily.

So, **here goes.** When you find a spare moment, would you mind:

* [Creating an account at The Beast's Lair](https://forums.nrvnqsr.com/register.php). This is easy! Also, this is annoying.
* [Commenting in the *Ultimate Edition* thread](https://forums.nrvnqsr.com/showthread.php/8229-Fate-Stay-Night-Realta-Nua-Ultimate-Edition). This is where things have a likely chance of going South rapidly. They're a *great* bunch of volunteer enthusiasts – but **(A)** they're grumpy more often than not and **(B)** they hate Linux.

If you *do* decide to take one for the Linux team by posting, please avoid mentioning Linux. (See **(B)** above.) Pertinent questions might include:

* "The *Ultimate Edition* installer fails to download patches, but Google Drive prevents me from manually doing so due to exceeding quota limits. Are there any alternative download links? A torrent? A Mega.io folder? A sketchy Russian-hosted filelocker named Allyourdataisbelongtous.ru?"
* "Is there an estimated ETA on the next stable release? Is there an unstable release that downloads patches better than the 0.9.1 release that I should just be using instead? Should I just spoil myself on the first route by watching the awful anime instead and then regretting my life?"

*...stuff like that.* I haven't kept abreast of developments at The Beast's Lair. However unlikely, they might have already resolved some or all of the above issues. Let's choose to believe what I am saying so we can sleep at night.

**Comment by kaasknak** [comment] 2021-07-20 22:05
I have tried signing up to the beast's lair. As you said indeed. It is an annoying process (there are fate related questions you have to answer but I am trying to get the patch so I can play it so I can answer the questions. Duckduckgo was my friend.). I have tried two different e-mail addresses and neither received the confirmation mail so I am going to hope it shows up later and I might have some time to check in again tomorrow (I am currently on vacation).

I'll keep you appraised.

**Comment by kaasknak** [comment] 2021-07-21 14:03
Great news!
I managed to acquire the patches.
I still haven't received an e-mail from the beast's lair but there is a (shitty) mirror.
https://www.mediafire.com/file/047tv8akannrti3/patch.zip/file this zipfile contains all the patches. Password of the zipfile is _ObviouslyFate_.
After patching I only had to disable Vulkan (I got the white screen with audio) and it seems to work now. Cursor behaviour is a bit weird but that might be caused by many things.
With this mirror available I think you can also close this issue. Just add the link to the README.md as a mirror and it should work.

You are an absolute legend by the way for writing a README that contains so many fixes for potential problems.

**Comment by kaasknak** [comment] 2021-07-22 04:52
#16 I took the liberty of sending a pull request that adds the mirror to the README.md

**Closed as completed** 2021-07-22 05:42 UTC

**Comment by leycec** [comment] 2021-07-22 07:16
> I still haven't received an e-mail from the beast's lair but there is a (shitty) mirror.

Indeed, this is Ilya-approved great news. No mirror can be shittier than Google Drive. That makes Mediafire the new only-working mirror and still-reigning champion! We now give thanks. Still, I kinda suspect this is what we were all hoping for:

*mega.io: a new contender has emerged*

> After patching I only had to disable Vulkan (I got the white screen with audio) and it seems to work now.

**Yay!** Vulkan, y u so logical but never work right?

> Cursor behaviour is a bit weird but that might be caused by many things.

Yes, the many things that are called **WINE.** Cursor desynchronization is still a common thing when running WINE-emulated apps under X.org; for reasons that were never clear to me, WINE was never able to get that right.

Running WINE-emulated apps under Wayland probably fixes that – but you can pry [my decades-old X.org FVWM configuration](https://www.fvwm.org/) from my cold, dead neckbeard hairs!

> You are an absolute legend by the way for writing a README that contains so many fixes for potential problems.

*ohyou* :blush: 

Thanks so much for your stupendous PR, by the way! That should go a long way to *finally* resolving everyone's main complaint with this whole thing.
